---
- include_role:
    name: k3s
- include_role:
    name: dt-operator
- name: app-easytrade
  include_tasks: "{{role_path}}/files/app-easytrade/tasks/main.yaml"
  vars:
    easytrade_role_path: "{{role_path}}/files/app-easytrade"
    easytrade_namespace: "easytrade"
    easytrade_image_tag: "5aa49fb"
    easytrade_headlessloadgen_tag: "848c2ab"
    easytrade_domain: "easytrade.{{ ingress_domain }}"
    easytrade_addDashboardLink: true
    easytrade_addDashboardPreview: true
- include_role:
    name: dashboard
