---
- include_role:
    name: k3s
- include_role:
    name: app-easytrade
  vars:
    manifest_strategy: "static" # static or fetch_latest: static will use the static files from the app-easytrade role, dynamic will clone the EasyTrade repository with the latest files. Attention: This would break the existing deployments if the EasyTrade repository is updated.
---
easytrade_namespace: "easytrade" # namespace that EasyTrade will be deployed in
easytrade_domain: "easytrade.{{ ingress_domain }}" #ingress domain for regular EasyTrade
easytrade_addDashboardLink: true # add a link to the dashboard when enabled
easytrade_addDashboardPreview: true # add a preview to the dashboard when enabled
easytrade_deploy: true # Choose to deploy or not easytrade. True by default but useful to set it to false when it is combined with gitlab or any other ci/cd, so it's gets deployed from the pipeline
easytrade_owner: "ace-box" # Customize the dt.owner annotation for your lab.
- include_role:
    name: dt-operator
easytrade_addDashboardLink: true
easytrade_addDashboardPreview: true
- include_role:
    name: dashboard
