---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: easytrade
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
  labels:
    app: easytrade
    app.kubernetes.io/managed-by: Helm
    chart: easytrade
    heritage: Helm
    release: easytrade
  name: easytrade
spec:
  rules:
  - host: {{ .Values.ingress.domain }}
    http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontendreverseproxy
                port:
                  number: 80