config: 
    - acebox: "private-synthetic.json"
  
acebox:
    - name: "ACE-BOX"
    - nodeId: "{{ .Env.SYNTH_NODE_ID }}"
    - skipDeployment: "{{ .Env.SKIP_SYNTH }}"
    - availabilityLocationOutage: "true"
    - availabilityNodeOutage: "false"
